apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  namespace: try-dapr
data:
  config: |-
    listeningport: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: try-dapr
spec:
  selector:
    matchLabels:
      app: server
  replicas: 2
  template:
    metadata:
      labels:
        app: server
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "server"
        dapr.io/port: "4000"
    spec:
      containers:
      - name: server
        # This is the import path for the Go binary to build and run.
        image: github.com/costap/dapr-try/cmd/server
        ports:
        - containerPort: 4000
        env:
        - name: "GRPC_GO_LOG_VERBOSITY_LEVEL"
          value: "99"
        - name: "GRPC_GO_LOG_SEVERITY_LEVEL"
          value: "info"
        - name: "CONFIG_PATH"
          value: "/etc/config"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
          requests:
            cpu: "250m"
            memory: "64Mi"
      volumes:
      - name: config-volume
        configMap:
          name: server-config
          items:
          - key: config
            path: config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: try-dapr
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000